version: "3.9"
services:
  server:
    build:
      context: ./
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGHOST: postgres
      PGPASSWORD: postgres
      PGDATABASE: crypto_portfolio_tracker
      PGPORT: 8000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: nodemon dist/app.js

  postgres:
    image: postgres:15.1
    restart: always
    command: postgres -c port=8000
    ports:
      - '8000:8000'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: crypto_portfolio_tracker
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  postgres:

