version: "3.9"
services:

  client:
    build:
      context: ./client
    ports:
      - '5173:5173'
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  server:
    build:
      context: ./
    tty: true
    ports:
      - '5000:5000'
    depends_on:
      - postgres
      - redis
    environment:
      PGUSER: postgres
      PGHOST: postgres
      PGPASSWORD: postgres
      PGDATABASE: crypto_portfolio_tracker
      PGPORT: 8000
      REDISPORT: 8001
      REDISHOST: redis
      PORT: 5000
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: nodemon -L dist/app.js

  postgres:
    image: postgres:15.1
    restart: always
    command: postgres -c port=8000
    ports:
      - '8000:8000'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: crypto_portfolio_tracker
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  
  redis:
    image: redis:7.0
    ports:
      - '8001:8001'
    command: ["redis-server", "--bind", "redis", "--port", "8001"]
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:

